### ISSUE TITLE
Use createQueue

### ISSUE THREAD

**Issue by semisight** [crossmasters/mhubcloud-gtm#1]
https://github.com/crossmasters/mhubcloud-gtm/blob/0dd5c67111dfc2a25701abb710c53296d31ac765/template.tpl#L185

I am not sure this will do what you think. I recommend using the [createQueue api function](https://developers.google.com/tag-platform/tag-manager/templates/api#createqueue) instead. It will do what you want.

**Comment by jhornych** [comment]
@semisight is it possible to see the source code of the template API somewhere?

**Comment by semisight** [comment]
Apologies for leaving this for so long. Currently it is not possible to do so. Is there special logic that you require for that queue?

**Comment by jhornych** [comment]
Yes it took a while :-) I actually did looked into the logic how it is done in the generated code, and you were right, we did fix it, just  did not publish it into the repo. Is this the requirement to make the template available in the gallery?

BTW, why you do not allow to modify the dataLayer form the template directly and wrap the message payload?

**Comment by semisight** [comment]
It's not technically a requirement, but your tag won't work until you make this change. Once you update your metadata.yaml to [a96949c](https://github.com/crossmasters/mhubcloud-gtm/commit/a96949c7daefb0e88a23a7264e7154f452586004), I'll merge this into the gallery.

We do allow modification! But only through the `create{Arguments}Queue` API. These APIs are slightly different than their name implies; if the queue already exists, it returns a pushFn for the existing queue on page. So if you call:

```javascript
// This line will create the queue...
const pushFn = createArgumentsQueue('someQueueThatDoesNotExist');
pushFn('first push');
// This line doesn't overwrite the queue! It just returns another push function
const pushFn2 = createArgumentsQueue('someQueueThatDoesNotExist');
pushFn2('second push');

// Contents of the queue are now: ['first push', 'second push']
```

**Comment by Brzobohaty** [comment]
@semisight I did change the code to use createQueue and also I updated metadata.yaml. Can you please merge it into the gallery?

**Comment by semisight** [comment]
Done and done.
